import markdown
import pdfkit
import os

html_template = """
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <style>
        body {{ font-family: Arial, sans-serif; line-height: 1.6; color: #333; margin: 40px; }}
        .header {{ text-align: center; margin-bottom: 50px; border-bottom: 2px solid #ddd; padding-bottom: 20px; }}
        .footer {{ text-align: center; font-size: 10px; color: #777; margin-top: 50px; border-top: 1px solid #ddd; padding-top: 10px; }}
        h1, h2, h3 {{ color: #2c3e50; }}
        table {{ border-collapse: collapse; width: 100%; margin-bottom: 20px; }}
        th, td {{ border: 1px solid #ddd; padding: 8px; text-align: left; }}
        th {{ background-color: #f2f2f2; }}
    </style>
</head>
<body>
    <div class="header">
        <h1>karumbu.in</h1>
        <p>Flat 1B, Harmony, New no 27, Old no 14, East Street, RR Colony, Ashok Nagar, Chennai 600083<br>
        Phone: +91 9025737344 | Email: gurudev@karumbu.in</p>
    </div>
    
    <div class="content">
        {content}
    </div>
    
    <div class="footer">
        Generated by Karumbu.in
    </div>
</body>
</html>
"""

def md_to_pdf(md_path, pdf_path):
    with open(md_path, 'r', encoding='utf-8') as f:
        text = f.read()
    
    html_content = markdown.markdown(text, extensions=['tables'])
    final_html = html_template.format(content=html_content)
    
    options = {
        'page-size': 'A4',
        'margin-top': '0.75in',
        'margin-right': '0.75in',
        'margin-bottom': '0.75in',
        'margin-left': '0.75in',
        'encoding': "UTF-8",
        'enable-local-file-access': None
    }
    
    pdfkit.from_string(final_html, pdf_path, options=options)
    print(f"Created {pdf_path}")

base = "/home/dev-dell/.gemini/antigravity/brain/fd58b605-665f-439b-8c14-ff649c6e2d59"
md_to_pdf(f"{base}/scope_dna_astrology.md", "Scope_DNA_Astrology_neurogenetics.my.pdf")
md_to_pdf(f"{base}/scope_clinic_website.md", "Scope_Holistic_Clinic_Website.pdf")
